import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Recipe Guider",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

// 한 페이지 이상의 셸을 정의하는 파일
// 하나의 layout 파일이 app 폴더 상단에 필요하다.
// 중첩된 layout.js 파일도 가질 수 있다.
// -> 그래서 about 폴더에 layout.tsx 파일을 만들어서 중첩된 레이아웃을 만들 수 있다.

// children은 페이지 컨텐츠를 나타낸다.
